version: '3.6'
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_VERSION: 7.4
    image: denner-client/php
    container_name: denner-common_php
    networks:
      - denner-client
    volumes:
      - .:/app
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
networks:
  denner-client:
    name: denner-client
